HOST: http://cinemadistance.eu01.aws.af.cm

--- goToCinema API ---
---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Movies
Related to the database & movie storage
--

Shows a list of all movies with their showtimes joined together
GET /movies
< 200
< Content-Type: application/json
[{"actori":"Cu:Leonardo DiCaprio,Carey Mulligan,Tobey Maguire","gen":"Gen film:Dramă,Romantic,Dragoste","id":1,
    "image":"http://static.cinemagia.ro/img/resize/db/movie/03/26/48/the-great-gatsby-763698l-80x0-w-49fa6bd0.jpg",
    "nota":"Notă 8.0 / Imdb 7.5","regizor":"Regizor:Baz Luhrmann",
    "titluEn":"The Great Gatsby (2013)",
    "titluRo":"Marele Gatsby","showtimes":[]},
    {"actori":"Cu:Chris Pine,Zoe Saldana,Zachary Quinto,John Cho,Benedict Cumberbatch",
    "gen":"Gen film:Acţiune,Aventuri,SF","id":2,
    "image":"http://static.cinemagia.ro/img/resize/db/movie/48/84/10/star-trek-into-darkness-941561l-80x0-w-6bdebb4b.jpg",
    "nota":"Notă 8.3 / Imdb 8.4","regizor":"Regizor:J.J. Abrams","titluEn":"Star Trek Into Darkness  (2013)",
    "titluRo":"Star Trek În întuneric 3D",
    "showtimes":[
        {"hour":"20:05","place":"Grand Cinema Digiplex"},
        {"hour":"21:30","place":"Hollywood Multiplex"},
        {"hour":"21:45","place":"Movieplex Cinema Plaza"},
        {"hour":"21:00","place":"Cinema City Cotroceni"},
        {"hour":"21:00","place":"Cinema City Cotroceni VIP"},
        {"hour":"20:30","place":"Cinema City Sun Plaza"},
        {"hour":"11:50","place":"Romtelecom IMAX"},
        {"hour":"17:20","place":"Romtelecom IMAX"},
        {"hour":"20:00","place":"Romtelecom IMAX"},
        {"hour":"22:40","place":"Romtelecom IMAX"}
        ]
}]
    

Shows specific info about a movie --- CAM REDUNDANT
GET /movies/{id}
< 200
< Content-Type: application/json
{
    "actori":"Cu:Leonardo DiCaprio,Carey Mulligan,Tobey Maguire",
    "created_at":"2013-05-14T17:07:12Z",
    "gen":"Gen film:Dramă,Romantic,Dragoste",
    "id":1,
    "image":"http://static.cinemagia.ro/img/resize/db/movie/03/26/48/the-great-gatsby-763698l-80x0-w-49fa6bd0.jpg",
    "nota":"Notă 8.0 / Imdb 7.5","regizor":"Regizor:Baz Luhrmann",
    "titluEn":"The Great Gatsby (2013)",
    "titluRo":"Marele Gatsby",
    "updated_at":"2013-05-14T17:07:12Z"
}

Shows all the showtimes for {id} movie --- CAM REDUNDANT
GET /movies/{id}/aparitii
< 200
< Content-Type: application/json
{
    "actori":"Cu:Chris Pine,Zoe Saldana,Zachary Quinto,John Cho,Benedict Cumberbatch",
    "gen":"Gen film:Acţiune,Aventuri,SF",
    "image":"http://static.cinemagia.ro/img/resize/db/movie/48/84/10/star-trek-into-darkness-941561l-80x0-w-6bdebb4b.jpg",
    "nota":"Notă 8.3 / Imdb 8.4","regizor":"Regizor:J.J. Abrams",
    "titluEn":"Star Trek Into Darkness  (2013)",
    "titluRo":"Star Trek În întuneric 3D",
    "showtimes":[
        {"hour":"20:05","place":"Grand Cinema Digiplex"},
        {"hour":"21:30","place":"Hollywood Multiplex"},
        {"hour":"21:45","place":"Movieplex Cinema Plaza"},
        {"hour":"21:00","place":"Cinema City Cotroceni"},
        {"hour":"21:00","place":"Cinema City Cotroceni VIP"},
        {"hour":"20:30","place":"Cinema City Sun Plaza"},
        {"hour":"11:50","place":"Romtelecom IMAX"},
        {"hour":"17:20","place":"Romtelecom IMAX"},
        {"hour":"20:00","place":"Romtelecom IMAX"},
        {"hour":"22:40","place":"Romtelecom IMAX"}
        ]
}

--
Users
The following is a section of resources related to the users & their tokens
--
Authenticates a user to the system, has <b> 3 </b> possible return values. It also generates an <b>AUTH_KEY</b> which is
stored in the database until the user is logged out.
<table>
    <tr>
        <td><b>loggedIn</b></td>
        <td><b>key</b></td>
        <td><b>error</b></td>
    </tr>
    <tr>
        <td>true</td>
        <td>AUTH_KEY</td>
        <td>-</td>
    </tr>
    <tr>
        <td>false</td>
        <td>-</td>
        <td>"email"</td>
    </tr>
    <tr>
        <td>false</td>
        <td>-</td>
        <td>"password"</td>
    </tr>
</table>
POST /user/login{?username,password}
< 200
< Content-Type: application/json
{ 
    "possible_responses": 
    [
        { "loggedIn" => true , "key" => AUTH_KEY , "user_id" => user.id },
        { "error" => "email"},
        { "error" => "password"}
    ]
}

Logs the user out of the system, has <b>3</b> possible reponses. It deleted the <b>AUTH_KEY</b> from the database.
<table>
    <tr>
        <td><b>logout</b></td>
        <td><b>error</b></td>
    </tr>
    <tr>
        <td>true</td>
        <td>-</td>
    </tr>
    <tr>
        <td>false</td>
        <td>"Token does not exist"</td>
    </tr>
    <tr>
        <td>false</td>
        <td>"Expecting a token parameter"</td>
    </tr>
</table>
GET /user/logout{?token}
< 200
< Content-Type: application/json
{
    "possible_responses": 
    [
        { "error" => "Token does not exist"},
        { "error" => "Expecting a token parameter"},
        { "logout" => true }
    ] 
}

Check if a token is valid, has <b>3</b> possible reponses.

<table>
    <tr>
        <td><b>token</b></td>
        <td><b>error</b></td>
    </tr>
    <tr>
        <td>true</td>
        <td>-</td>
    </tr>
    <tr>
        <td>false</td>
        <td></td>
    </tr>
    <tr>
        <td>false</td>
        <td>"Expecting a token parameter"</td>
    </tr>
</table>

GET /user/checkToken{?token}
< 200
< Content-Type: application/json
{ 
    "possible_responses": 
    [
        { "token" => false },
        { "error" => "Expecting a token parameter"},
        { "token" => true }
    ] 
}

Searches the users for name/surname like the one supplied in the q paramater
GET /user/search{?q}
< 200
< Content-Type: application/json
[
    {
        "id":1,
        "nume":"Stoica",
        "prenume":"Alex",
        "username":"alex"
    },
    {
        "id":2,
        "nume":"Stoica",
        "prenume":"Vlad",
        "username":"vlad"
    }
]

Posts all the users posts.
GET /user/{id}/posts
< 200
< Content-Type: application/json
{
    "fullname":"Stoica Alex",
    "posts":[
        {
            "content":"mare baws",
            "receiver_id":2,
            "title":"test2"
        },
        {
            "content":"i haz contents",
            "receiver_id":1,
            "title":"dayum title"
        }]
}

Posts all the entries for a user's wall
GET /user/{id}/wall
< 200
< Content-Type: application/json
{
    "id":1,
    "fullname":"Stoica Alex",
    "wall_posts":[
        {
            "content":"content postare",
            "title":"titlu postare",
            "sender":{"fullname":"Stoica Vlad"}
        },
        {
            "content":"i haz contents",
            "title":"dayum title",
            "sender":{"fullname":"Stoica Alex"}
            
        }]
}

--
Distance calculator 
This provides with 3 methods of calculating the distance between the user and the cinemas.
--

GET distance/googleMaps{?lat,lng}
< 200
< Content-Type: application/json
[ { "distance" : "7.9km" , "duration" : 1495 ,"name" : "Movieplex" } ]

GET distance/openMaps{?lat,lng}
< 200
< Content-Type: application/json
[ { "distance" : "7.9km" , "duration" : 1495 ,"name" : "Movieplex" } ]

GET distance/{?lat,lng}
< 200
< Content-Type: application/json
[ { "distance" : "7.9km" , "duration" : 1495 ,"name" : "Movieplex" } ]